### PR TITLE
Fix a bug where if the variants of a job had different list of metas

### LINKED ISSUE #151: Wrong permutations table when the variant's metadata are not in the same format
For example, given 2 variants one with meta[jdk=1.8] and the other with meta[image=java:7], the web ui will show a single column jdk with one row for every value.

### PR DESCRIPTION
**Pull request by jawher**
(one with `go:1.4` and another with `image:my-image` for example), the job would group both in one single column

Fixes #151

### CODE REVIEW

File: web/src/job/jobController.js [hunk 1]
```diff
@@ -94,36 +94,49 @@ angular.module('bzk.job').controller('JobController', function($scope, BzkApi, $
...
-        var metaLabels = [],
+        var metaList = [],
             colors = {};
         if (variants.length > 0) {
-            var vref = variants[0];
-            _.each(vref.metas, function(m) {
-                metaLabels.push(m.kind == 'env' ? '$' + m.name : m.name);
+            var visitedMeta = {};
+            _.each(variants, function(v) {
+                v.metaMap = _.indexBy(v.metas, 'name')
```
Comment (haklop) [inline web/src/job/jobController.js]: Missing semicolon

File: web/src/job/jobController.js [hunk 2]
```diff
@@ -94,36 +94,49 @@ angular.module('bzk.job').controller('JobController', function($scope, BzkApi, $
...
                 var colIdx = 0;
                 _.each(variants, function(v) {
-                    var val = v.metas[i].value;
-                    if (!mcolors[val]) {
-                        mcolors[val] = colorsDb[colIdx];
-                        if (colIdx < colorsDb.length - 1) {
-                            colIdx++;
+                    var vm = _.findWhere(v.metas, {
+                        name: m.name
+                    })
```
Comment (haklop) [inline web/src/job/jobController.js]: Missing semicolon
