### PR TITLE
Prompt BZK env vars when none found

### LINKED ISSUE #139: Prompt BZK env vars when none found
When running `bzk` for the first, we don't expect to fail because of some missing environment variables. We should prompt the user in the CLI when none is found and maybe create a `.bzk` file at the home root with these env vars

### PR DESCRIPTION
**Pull request by julienvey**
Closes #139

### CODE REVIEW

File: cli/bzk/run.go [hunk 1]
```diff
@@ -48,12 +47,34 @@ func run(cmd *cli.Cmd) {
...
-			log.Fatal("$BZK_HOME environment variable is needed (or use --home option)")
+			if len(config.Home) == 0 {
+				*bzkHome = interactiveInput("Bazooka Home Folder")
+				config.Home = *bzkHome
+			}
+		}
+
+		if len(*dockerSock) == 0 {
+			if len(config.DockerSock) == 0 {
+				*dockerSock = interactiveInput("Bazooka Home Folder")
```
Comment (haklop) [inline cli/bzk/run.go]: Description is wrong!

**Comment by julienvey** [comment]
Fixed
